// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsavvyniyxnlmbkbzyfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzYXZ2eW5peXhubG1ia2J6eWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDMyODgsImV4cCI6MjA2MzU3OTI4OH0.o-0dovXu9llM-_GEnnnwnIndomf_4b-PavK9knOw3xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);